### ISSUE TITLE
Support for Gaposa / Kaiser Nienhaus Blinds

### ISSUE THREAD

**Issue by DerChrisBo** [andyboeh/mediola2mqtt#21]
Hey there, 
I think I got the Addon installed correctly, but as Gaposa Blinds / Kaiser Nienhaus Blinds aren't supported yet, I wanted to ask for some extension of your code for supported devices.

How can I help?

Thanks in advance!

**Comment by rorso** [comment]
As this addon is a mediator between MQTT and the Mediola-Gateway, it depends mostly on whether the blinds are already manageable via that one. 

[https://doku.mediola.com/doku.php?id=de:iqontrol:kaisernienhausmercato](https://doku.mediola.com/doku.php?id=de:iqontrol:kaisernienhausmercato)

In this case you may trace the network traffic between the Mediola IQONTROL App and the Mediola-Gateway API and capture the relevant commands with [Wireshark](https://www.wireshark.org).

The commands FROM the app TO the Gateway are essential. Any response or status broadcast FROM the gateway is highly interesting. If not obvious it should be enough traffic to separate different device addresses and the various commands.

Since you need a fully working setup of just these elements to get these informations, this part can only be done by you ;-)

Having these commands, it should be able to simulate them, as the Mediola app does nothing else. The magic of the remote protocol is done by the mediola gateway, once you know how to trigger it via the API.

You might start by calling the API on your Mediola from any browser and request some device status informations (use the IP address of your Mediola Gateway:

[http://192.168.0.123/cmd?XC_FNC=GetStates&config=1](http://192.168.0.123/cmd?XC_FNC=GetStates&config=1)

**Comment by andyboeh** [comment]
There is actually an easier way: Get access to the v5 API documentation at https://api.mediola.com/v5/ and check if "Dooya 2 (Kaiser Nienhaus)" works. Most of the commands work on the v4 and v6 gateways as well.

**Comment by DerChrisBo** [comment]
Thanks for your responses so far. The API is actually in Beta, but I applied for it anyways, perhaps there is something that might help.

I looked already in the HTTP-Commands and did not get the devices via XC_FNC=GetStates. Only the event-routines were showing.
The blinds are corretly set up via the mediola AIO Gateway and fully controllabe, so this should not be a problem. It might be neccessary to expose the devices somehow, but I didn't find anything about something like this.

I'll keep you posted, if I could it get to work via the API.

EDIT: Closing this for now. Thanks so far!
